"""initial schema

Revision ID: 933d9c7c6103
Revises: 
Create Date: 2026-09-09 00:29:16.579830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '933d9c7c6103'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('api_keys',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=12), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('models',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('framework', sa.Enum('PYTORCH', 'ONNX', name='modelframework'), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('UPLOADING', 'VALIDATING', 'READY', 'INVALID', name='modelstatus'), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('input_shape', sa.String(length=255), nullable=True),
    sa.Column('output_shape', sa.String(length=255), nullable=True),
    sa.Column('input_names', sa.String(length=500), nullable=True),
    sa.Column('output_names', sa.String(length=500), nullable=True),
    sa.Column('validation_error', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_user_id'), 'models', ['user_id'], unique=False)
    op.create_table('conversion_jobs',
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('target_format', sa.Enum('TFLITE', 'TENSORRT', 'COREML', name='targetformat'), nullable=False),
    sa.Column('optimization', sa.Enum('FP32', 'FP16', 'INT8', name='optimizationtype'), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'VALIDATING', 'CONVERTING', 'OPTIMIZING', 'BENCHMARKING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('target_device', sa.String(length=100), nullable=False),
    sa.Column('input_shape', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(length=4000), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversion_jobs_model_id'), 'conversion_jobs', ['model_id'], unique=False)
    op.create_index(op.f('ix_conversion_jobs_status'), 'conversion_jobs', ['status'], unique=False)
    op.create_table('benchmarks',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('model_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('latency_mean_ms', sa.Float(), nullable=True),
    sa.Column('latency_median_ms', sa.Float(), nullable=True),
    sa.Column('latency_p95_ms', sa.Float(), nullable=True),
    sa.Column('throughput_ips', sa.Float(), nullable=True),
    sa.Column('accuracy_pct', sa.Float(), nullable=True),
    sa.Column('memory_usage_mb', sa.Float(), nullable=True),
    sa.Column('benchmark_device', sa.String(length=100), nullable=False),
    sa.Column('unsupported_metrics', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['conversion_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_benchmarks_job_id'), 'benchmarks', ['job_id'], unique=False)
    op.create_table('conversion_artifacts',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('format', sa.Enum('TFLITE', 'TENSORRT', 'COREML', name='targetformat'), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['conversion_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversion_artifacts_job_id'), 'conversion_artifacts', ['job_id'], unique=False)
    op.create_table('job_logs',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('level', sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', name='loglevel'), nullable=False),
    sa.Column('message', sa.String(length=4000), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['conversion_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_logs_job_id'), 'job_logs', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_logs_timestamp'), 'job_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_logs_timestamp'), table_name='job_logs')
    op.drop_index(op.f('ix_job_logs_job_id'), table_name='job_logs')
    op.drop_table('job_logs')
    op.drop_index(op.f('ix_conversion_artifacts_job_id'), table_name='conversion_artifacts')
    op.drop_table('conversion_artifacts')
    op.drop_index(op.f('ix_benchmarks_job_id'), table_name='benchmarks')
    op.drop_table('benchmarks')
    op.drop_index(op.f('ix_conversion_jobs_status'), table_name='conversion_jobs')
    op.drop_index(op.f('ix_conversion_jobs_model_id'), table_name='conversion_jobs')
    op.drop_table('conversion_jobs')
    op.drop_index(op.f('ix_models_user_id'), table_name='models')
    op.drop_table('models')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
